
const AbstractSQL = require("../abstract");
const SqlString = require('sqlstring');
const {LiveSessions: {FIELDS: LIVE_SESSIONS_FIELDS, TABLE_NAME: LIVE_SESSIONS_TABLE_NAME}} = require("../../model/child");
const {Product: {SCHEMA: {FIELDS: PRODUCT_FIELDS, TABLE_NAME: PRODUCT_TABLE_NAME}}} = require("../../model/child");
const {AdminUsers: {FIELDS: ADMIN_USERS_FIELDS, TABLE_NAME: ADMIN_USERS_TABLE_NAME}} = require("../../model/child");

class LiveSessions extends AbstractSQL{
  constructor(siteId){
    super(siteId);
    this.tableName = LIVE_SESSIONS_TABLE_NAME;
    this.connection = super.connection();
  }
  
  async fetchSessions(siteId){
    const query = `SELECT LS.${LIVE_SESSIONS_FIELDS.SESSION_ID}, LS.${LIVE_SESSIONS_FIELDS.PRODUCT_ID}, 
    LS.${LIVE_SESSIONS_FIELDS.SCHEDULED_AT}, LS.${LIVE_SESSIONS_FIELDS.SESSION_ID}, LS.${LIVE_SESSIONS_FIELDS.HOST_USER_ID}, 
    LS.${LIVE_SESSIONS_FIELDS.STATUS}, LS.${LIVE_SESSIONS_FIELDS.TITLE}, 
    LS.${LIVE_SESSIONS_FIELDS.DESCRIPTION}, LS.${LIVE_SESSIONS_FIELDS.CREATED_BY}, 
    LS.${LIVE_SESSIONS_FIELDS.SCHEDULED_DURATION}, LS.${LIVE_SESSIONS_FIELDS.SESSION_ID},
    P.${PRODUCT_FIELDS.NAME} AS ${PRODUCT_TABLE_NAME}_${PRODUCT_FIELDS.NAME},
    P.${PRODUCT_FIELDS.DESCRIPTION} AS ${PRODUCT_TABLE_NAME}_${PRODUCT_FIELDS.DESCRIPTION},
    P.${PRODUCT_FIELDS.IMAGES} AS ${PRODUCT_TABLE_NAME}_${PRODUCT_FIELDS.IMAGES},
    P.${PRODUCT_FIELDS.MOBILE_IMAGES} AS ${PRODUCT_TABLE_NAME}_${PRODUCT_FIELDS.MOBILE_IMAGES},
    U.${ADMIN_USERS_FIELDS.FIRST_NAME} AS \`${ADMIN_USERS_TABLE_NAME}_${ADMIN_USERS_FIELDS.FIRST_NAME}\`,
    U.${ADMIN_USERS_FIELDS.LAST_NAME} AS \`${ADMIN_USERS_TABLE_NAME}_${ADMIN_USERS_FIELDS.LAST_NAME}\`
    FROM ${this.tableName} AS LS
    LEFT JOIN ${PRODUCT_TABLE_NAME} AS P ON P.${PRODUCT_FIELDS.ID} = LS.${LIVE_SESSIONS_FIELDS.PRODUCT_ID}
    LEFT JOIN \`${ADMIN_USERS_TABLE_NAME}\` AS U ON U.${ADMIN_USERS_FIELDS.ID} = LS.${LIVE_SESSIONS_FIELDS.HOST_USER_ID}
    WHERE LS.${LIVE_SESSIONS_FIELDS.SITE_ID} = ?`;
    return await this.connection.query(SqlString.format(query, [siteId]), super.getQueryType('SELECT'));
  }
}

module.exports = LiveSessions;
