const KEYS = {
  SSO_TOKEN: `SSO_TOKEN:{token}`,
  UNIQUE_INDENTIFIER_EMAIL: `UNIQUE_INDENTIFIER_EMAIL:{email}`,
  USER_BASIC_INFO: `USER_BASIC_INFO:{userId}`,
  SIGN_UP_TOKEN: `SIGN_UP_TOKEN:{token}`,
  RESET_PASSWORD_TOKEN: `RESET_PASSWORD_TOKEN:{token}`
};

module.exports = KEYS;