const CONSTANTS = {};

CONSTANTS.ALLOWED_GENDERS = {
  MALE: 'male',
  FEMALE: 'female',
  PREFER_NOT_TO_SAY: "preferNotToSay",
  OTHER: 'other'
}

CONSTANTS.GENDERS_LABEL = {
  [CONSTANTS.ALLOWED_GENDERS.MALE]: 'Male',
  [CONSTANTS.ALLOWED_GENDERS.FEMALE]: 'Female',
  [CONSTANTS.ALLOWED_GENDERS.PREFER_NOT_TO_SAY]: 'Prefer Not To Say',
  [CONSTANTS.ALLOWED_GENDERS.OTHER]: 'Other',
}

module.exports = CONSTANTS;