module.exports = {
  Menu: require("./menu"),
  Comment: require("./comment"),
  LikeVideo: require("./likeVideo"),
  MenuVideo: require("./menuVideo"),
  ProductVideo: require("./productVideo"),
  ProductMenus: require("./productMenus"),
  ProductMenuEntity: require("./productMenuEntity"),
  Metadata: require("./metadata"),
  Video: require("./video"),
  Users: require("./users"),
  AdminUsers: require("./adminUsers"),
  Product: require("./product"),
  Review: require("./review"),
  CommentThumb: require('./commentThumb'),
  LiveSessions: require('./liveSessions'),
  Pages: require('./pages'),
  Category: require('./category'),
}