module.exports = {
  Menu: require("./menu"),
  Comment: require("./comment"),
  LikeVideo: require("./likeVideo"),
  MenuVideo: require("./menuVideo"),
  ProductVideos: require("./productVideos"),
  ProductImages: require("./productImages"),
  Variants: require("./variants"),
  ProductMenus: require("./productMenus"),
  ProductThumb: require("./ProductThumb"),
  ProductMenuEntity: require("./productMenuEntity"),
  Metadata: require("./metadata"),
  Users: require("./users"),
  AdminUsers: require("./adminUsers"),
  Product: require("./product"),
  Review: require("./review"),
  CommentThumb: require('./commentThumb'),
  LiveSessions: require('./liveSessions'),
  Pages: require('./pages'),
  Category: require('./category'),
}