module.exports = {
  Menu: require("./menu"),
  Comment: require("./comment"),
  Cart: require("./cart"),
  LikeVideo: require("./likeVideo"),
  MenuVideo: require("./menuVideo"),
  ProductVideos: require("./productVideos"),
  ProductImages: require("./productImages"),
  Variants: require("./variants"),
  ProductMenus: require("./productMenus"),
  ProductThumb: require("./ProductThumb"),
  ProductMenuEntity: require("./productMenuEntity"),
  Metadata: require("./metadata"),
  Users: require("./users"),
  AdminUsers: require("./adminUsers"),
  Product: require("./product"),
  Review: require("./review"),
  CommentThumb: require('./commentThumb'),
  LiveSessions: require('./liveSessions'),
  Pages: require('./pages'),
  Category: require('./category'),
  ProductSave:require('./saveProduct'),
  Address:require('./address'),
  Payments: require('./payments'),
  PaymentMethods:require('./paymentmethods'),
  Orders:require('./orders'),
  OrderDetails:require('./orderDetails'),
  Countries:require('./countries'),
  States:require("./states"),
  Cities:require("./city"),
  Banner:require("./banner")
}